### PR TITLE
Issue#22 - generate-swagger destination-path parameter issue

### PR DESCRIPTION
**Pull request by fizaashraf37**
The issue was due to the below line of code in Generator class line 53

`self.file = open(destination_path, 'w')`

If user does not provides the destination path parameter then it is None and line 46 and 47 set self.destination_path to current directory path if it is None. This line should be as below to fix this. 

`self.file = open(self.destination_path, 'w')`

### CODE REVIEW

**Comment by fizaashraf37** [comment]
I am first time contributor to this project. I request maintainers to approve running workflow for my PR and allow me to do contribution to this project.

**Comment by MDUYN** [comment]
Thanks @fizaashraf37. I think you should now be maintainer of the repo. Maybe you can add this to the develop branch and add some tests

**Review by fizaashraf37 — COMMENTED** [review]
@MDUYN , kindly approve this PR as I cannot approve my own PR.

**Comment by fizaashraf37** [comment]
I have also added test cases. But these are failing on Git although these are running without issues locally.

**Review by MDUYN — COMMENTED** [review]
Changes look good

**Comment by fizaashraf37** [comment]
I have fixed this. Had to update the reference file as previous merged PR related to nested schemas was adding examples in schemas in generated file. So reference and generated files were mismatching.

**Review by MDUYN — APPROVED** [review]

**Pull request merged**
